version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress1
      - wordpress2

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    depends_on:
      - mariadb_replica
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    depends_on:
      - mariadb_replica
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  mariadb_master:
    image: mariadb:latest
    container_name: mariadb_master
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MASTER_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_MASTER_DATABASE}
      MYSQL_USER: ${MYSQL_MASTER_USER}
      MYSQL_PASSWORD: ${MYSQL_MASTER_PASSWORD}
    volumes:
      - master_db_data:/var/lib/mysql
      - ./masterdb/masterdb.cnf:/etc/mysql/conf.d/mysql.cnf
    # command: /var/lib/initial.sh

  mariadb_replica:
    image: mariadb:latest
    container_name: mariadb_replica
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_REPLICA_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_REPLICA_DATABASE}
      MYSQL_USER: ${MYSQL_REPLICA_USER}
      MYSQL_PASSWORD: ${MYSQL_REPLICA_PASSWORD}
    depends_on:
      - mariadb_master
    volumes:
      - replica_db_data:/var/lib/mysql
      - ./replica_db/replicadb.cnf:/etc/mysql/conf.d/mysql.cnf
    # command: /var/lib/initial.sh
volumes:
  wordpress_data:
  master_db_data:
  replica_db_data:
