version: 3.8

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - 80:80
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress1
      - wordpress2

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    hostname: wordpress1
    networks:
      - cangrownet
    depends_on:
      - mariadb_replica
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST: ${MASTER_DB_HOST}
      - WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    hostname: wordpress2
    networks:
      - cangrownet
    depends_on:
      - mariadb_replica
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST: ${MASTER_DB_HOST}
      - WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  mariadb_master:
    image: mariadb:latest
    container_name: mariadb_master
    hostname: ${MASTER_DB_HOST}
    networks:
      - cangrownet
    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_MASTER_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${MYSQL_MASTER_DATABASE}
      - MYSQL_USER: ${MYSQL_MASTER_USER}
      - MYSQL_PASSWORD: ${MYSQL_MASTER_PASSWORD}
    volumes:
      - master_db_data:/var/lib/mysql
      - $PWD/masterdb/masterdb.cnf:/etc/mysql/conf.d/masterdb.cnf
    ports:
      - "3306:3306"

  mariadb_replica:
    image: mariadb:latest
    container_name: mariadb_replica
    hostname: mariadb_replica
    networks:
      - cangrownet
    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_REPLICA_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${MYSQL_REPLICA_DATABASE}
      - MYSQL_USER: ${MYSQL_REPLICA_USER}
      - MYSQL_PASSWORD: ${MYSQL_REPLICA_PASSWORD}
    depends_on:
      - mariadb_master
    volumes:
      - replica_db_data:/var/lib/mysql
      - $PWD/replicadb/replicadb.cnf:/etc/mysql/conf.d/replicadb.cnf
    ports:
      - "3307:3306"


volumes:
  wordpress_data:
  master_db_data:
  replica_db_data:
networks:
  cangrownet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/28"
          gateway: "192.168.0.1"
