version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress1
      - wordpress2

  wordpress1:
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  wordpress2:
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  mariadb_master:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MASTER_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_MASTER_DATABASE}
      MYSQL_USER: ${MYSQL_MASTER_USER}
      MYSQL_PASSWORD: ${MYSQL_MASTER_PASSWORD}
    restart: "no"
    entrypoint: /masterdb/initial.sh

  mariadb_replica:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_REPLICA_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_REPLICA_DATABASE}
      MYSQL_USER: ${MYSQL_REPLICA_USER}
      MYSQL_PASSWORD: ${MYSQL_REPLICA_PASSWORD}
    restart: "no"
    entrypoint: /replicadb/initial.sh
volumes:
  wordpress_data:
