version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress1
      - wordpress2

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    depends_on:
      - mariadb_replica
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - "WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}"
      - "WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}"
      - "WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}"
      - "WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}"

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    depends_on:
      - mariadb_replica
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - "WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}"
      - "WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}"
      - "WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}"
      - "WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}"

  mariadb_master:
    image: mariadb:latest
    container_name: mariadb_master
    environment:
      - "MARIADB_ROOT_PASSWORD: ${MARIADB_MASTER_ROOT_PASSWORD}"
      - "MARIADB_DATABASE: ${MARIADB_MASTER_DATABASE}"
      - "MARIADB_USER: ${MARIADB_MASTER_USER}"
      - "MARIADB_PASSWORD: ${MARIADB_MASTER_PASSWORD}"
    volumes:
      - master_db_data:/var/lib/MARIADB
      - ./masterdb/masterdb.cnf:/etc/MARIADB/conf.d/MARIADB.cnf
    # command: /var/lib/initial.sh

  mariadb_replica:
    image: mariadb:latest
    container_name: mariadb_replica
    environment:
      - "MARIADB_ROOT_PASSWORD: ${MARIADB_REPLICA_ROOT_PASSWORD}"
      - "MARIADB_DATABASE: ${MARIADB_REPLICA_DATABASE}"
      - "MARIADB_USER: ${MARIADB_REPLICA_USER}"
      - "MARIADB_PASSWORD: ${MARIADB_REPLICA_PASSWORD}"
    depends_on:
      - mariadb_master
    volumes:
      - replica_db_data:/var/lib/MARIADB
      - ./replicadb/replicadb.cnf:/etc/MARIADB/conf.d/MARIADB.cnf
    # command: /var/lib/initial.sh
volumes:
  wordpress_data:
  master_db_data:
  replica_db_data:
