version: "3.8"

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    networks:
      - fastpressnet
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress1
      - wordpress2

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    hostname: wordpress1
    networks:
      - fastpressnet
    depends_on:
      - proxysql
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${PROXYSQL_DB_HOST}:6033
      WORDPRESS_DB_USER: ${SHARED_USER_NAME}
      WORDPRESS_DB_PASSWORD: ${SHARED_USER_PASSWORD}
      WORDPRESS_DB_NAME: ${MASTER_DATABASE}

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    hostname: wordpress2
    networks:
      - fastpressnet
    depends_on:
      - proxysql
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${PROXYSQL_DB_HOST}:6033
      WORDPRESS_DB_USER: ${SHARED_USER_NAME}
      WORDPRESS_DB_PASSWORD: ${SHARED_USER_PASSWORD}
      WORDPRESS_DB_NAME: ${MASTER_DATABASE}

  wordpress3:
    image: wordpress:latest
    container_name: wordpress3
    hostname: wordpress3
    networks:
      - fastpressnet
    depends_on:
      - proxysql
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${PROXYSQL_DB_HOST}:6033
      WORDPRESS_DB_USER: ${SHARED_USER_NAME}
      WORDPRESS_DB_PASSWORD: ${SHARED_USER_PASSWORD}
      WORDPRESS_DB_NAME: ${MASTER_DATABASE}

  proxysql:
    image: proxysql/proxysql:latest
    container_name: proxysql
    restart: always
    hostname: ${PROXYSQL_DB_HOST}
    networks:
      - fastpressnet
    ports:
      - 5432:5432
    environment:
      MARIADB_ROOT_PASSWORD: ${PROXYSQL_ROOT_PASSWORD}
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mariadb_replica

  mariadb_master:
    image: mariadb:latest
    container_name: mariadb_master
    restart: always
    hostname: ${MASTER_DB_HOST}
    networks:
      - fastpressnet
    environment:
      MARIADB_ROOT_PASSWORD: ${MASTER_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MASTER_DATABASE}
      MARIADB_USER: ${MASTER_USER}
      MARIADB_PASSWORD: ${MASTER_PASSWORD}
    volumes:
      - master_db_data:/var/lib/mysql
      - ./masterdb/masterdb.cnf:/etc/mysql/conf.d/masterdb.cnf

  mariadb_replica:
    image: mariadb:latest
    restart: always
    container_name: mariadb_replica
    hostname: mariadb_replica
    networks:
      - fastpressnet
    environment:
      MARIADB_ROOT_PASSWORD: ${REPLICA_ROOT_PASSWORD}
      MARIADB_USER: ${REPLICA_USER}
      MARIADB_PASSWORD: ${REPLICA_PASSWORD}
    depends_on:
      - mariadb_master
    volumes:
      - replica_db_data:/var/lib/mysql
      - ./replicadb/replicadb.cnf:/etc/mysql/conf.d/replicadb.cnf  

volumes:
  wordpress_data:
  master_db_data:
  replica_db_data:
networks:
  fastpressnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/28"
          gateway: "192.168.0.1"
