version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    networks:
      - cangrownet
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress1
      - wordpress2

  wordpress1:
    image: wordpress:latest
    container_name: wordpress1
    hostname: wordpress1
    networks:
      - cangrownet
    depends_on:
      - proxysql
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${PROXYSQL_DB_HOST}:6033
      WORDPRESS_DB_USER: ${SHARED_USER_NAME}
      WORDPRESS_DB_PASSWORD: ${SHARED_USER_PASSWORD}
      WORDPRESS_DB_NAME: ${MASTER_DATABASE}

  wordpress2:
    image: wordpress:latest
    container_name: wordpress2
    hostname: wordpress2
    networks:
      - cangrownet
    depends_on:
      - proxysql
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${PROXYSQL_DB_HOST}:6033
      WORDPRESS_DB_USER: ${SHARED_USER_NAME}
      WORDPRESS_DB_PASSWORD: ${SHARED_USER_PASSWORD}
      WORDPRESS_DB_NAME: ${MASTER_DATABASE}

  proxysql:
    image: proxysql/proxysql:latest
    container_name: proxysql
    hostname: ${PROXYSQL_DB_HOST}
    networks:
      - cangrownet
    ports:
      - "16032:6032"
      - "16033:6033"
      - "16070:6070"
    environment:
      MYSQL_ROOT_PASSWORD: ${PROXYSQL_ROOT_PASSWORD}
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
      # - ./.env:/docker-entrypoint-initdb.d/.env
      # - ./proxysql/initial.sh:/docker-entrypoint-initdb.d/initial.sh
    depends_on:
      - mariadb_replica

  mariadb_master:
    image: mariadb:latest
    container_name: mariadb_master
    hostname: ${MASTER_DB_HOST}
    networks:
      - cangrownet
    environment:
      MYSQL_ROOT_PASSWORD: ${MASTER_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MASTER_DATABASE}
      MYSQL_USER: ${MASTER_USER}
      MYSQL_PASSWORD: ${MASTER_PASSWORD}
    volumes:
      - master_db_data:/var/lib/mysql
      - ./masterdb/masterdb.cnf:/etc/mysql/conf.d/masterdb.cnf
      # - ./.env:/docker-entrypoint-initdb.d/.env
      # - ./masterdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  mariadb_replica:
    image: mariadb:latest
    container_name: mariadb_replica
    hostname: mariadb_replica
    networks:
      - cangrownet
    environment:
      MYSQL_ROOT_PASSWORD: ${MASTER_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MASTER_DATABASE}
      MYSQL_USER: ${MASTER_USER}
      MYSQL_PASSWORD: ${MASTER_PASSWORD}
    depends_on:
      - mariadb_master
    volumes:
      - replica_db_data:/var/lib/mysql
      - ./replicadb/replicadb.cnf:/etc/mysql/conf.d/replicadb.cnf
      # - ./.env:/docker-entrypoint-initdb.d/.env
      # - ./replicadb:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

volumes:
  wordpress_data:
  master_db_data:
  replica_db_data:
networks:
  cangrownet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/28"
          gateway: "192.168.0.1"
